#!/usr/bin/env python3
"""
Fetch ~1 month of daily closes for the news page's "Jensen Huang concept stocks"
and write a static snapshot to data/stocks.js for the inline-SVG sparklines.

Source: Yahoo Finance chart API (no key). Tickers are read from data/news.js
(the stocks section's item slugs) so this stays in sync with the page.

Run: uv run --no-project python _tools/build_stocks.py
Out: data/stocks.js  window.STOCKS = { generated, range, series:{ticker:{c,cur,pct}} }
"""
import datetime
import json
import os
import time
import urllib.error
import urllib.request

from venue_match import load_js_obj

HERE = os.path.dirname(__file__)
DATA = os.path.normpath(os.path.join(HERE, "..", "data"))
API = "https://query1.finance.yahoo.com/v8/finance/chart/{t}?range=1mo&interval=1d"
UA = "Mozilla/5.0 (compatible; computex-site/1.0)"


def tickers():
    secs = load_js_obj(os.path.join(DATA, "news.js"), name="SITE_SECTIONS")
    stocks = next(s for s in secs if s.get("id") == "stocks")
    return [it["slug"] for it in stocks["items"] if it.get("slug")]


def _get(ticker):
    req = urllib.request.Request(API.format(t=ticker), headers={"User-Agent": UA})
    for attempt in (1, 2, 3):
        try:
            with urllib.request.urlopen(req, timeout=20) as resp:
                return json.load(resp)
        except urllib.error.HTTPError as e:
            if e.code == 404:
                raise            # deterministic — don't retry
            if attempt == 3:
                raise
            time.sleep(1.5)
        except Exception:
            if attempt == 3:
                raise
            time.sleep(1.5)


def fetch(ticker):
    try:
        j = _get(ticker)
    except urllib.error.HTTPError as e:
        # listed code not on TWSE — try the OTC (.TWO) board
        if e.code == 404 and ticker.endswith(".TW"):
            j = _get(ticker[:-3] + ".TWO")
        else:
            raise
    res = j["chart"]["result"][0]
    closes = res["indicators"]["quote"][0]["close"]
    stamps = res["timestamp"]
    # keep only days with a real close, paired with their date (YYYY-MM-DD)
    pairs = [(datetime.datetime.fromtimestamp(ts, datetime.UTC).strftime("%Y-%m-%d"), c)
             for ts, c in zip(stamps, closes) if c is not None]
    closes = [round(c, 2) for _, c in pairs]
    dates = [d for d, _ in pairs]
    cur = res["meta"].get("currency", "")
    pct = round((closes[-1] - closes[0]) / closes[0] * 100, 2) if len(closes) >= 2 and closes[0] else 0.0
    return {"c": closes, "cur": cur, "pct": pct}, (dates[-1] if dates else "")


def main():
    series, last_date = {}, ""
    for tk in tickers():
        try:
            data, ld = fetch(tk)
            series[tk] = data
            last_date = max(last_date, ld)
            arrow = "▲" if data["pct"] >= 0 else "▼"
            print(f"  {tk:<10} {len(data['c']):>2}d  {arrow}{abs(data['pct']):>5}%  {data['cur']}")
        except Exception as e:
            print(f"  ! {tk}: {e}")
        time.sleep(0.4)   # be gentle on the API between symbols

    obj = {"generated": last_date, "range": "1mo", "series": series}
    path = os.path.join(DATA, "stocks.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* 黃仁勳概念股近一個月日線收盤快照(sparkline 用)。\n")
        f.write("   來源:Yahoo Finance chart API。AUTO-GENERATED by _tools/build_stocks.py。\n")
        f.write("   重跑更新:uv run --no-project python _tools/build_stocks.py */\n")
        f.write("window.STOCKS = ")
        json.dump(obj, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"\n{len(series)}/{len(tickers())} 檔 · 截至 {last_date} · {os.path.getsize(path)} bytes")


if __name__ == "__main__":
    main()
